[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["database.sqlite"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
